# Project information
site_name: GeoNetwork opensource
site_description: GeoNetwork catalogue for listing, searching and reviewing records.
site_dir: target/html
#site_url: https://docs.geonetwork-opensource.org/
site_url: https://silkov78.github.io/geonetwork-html-ru/

# Repository
repo_name: core-geonetwork
repo_url: https://github.com/geonetwork/core-geonetwork
edit_uri: edit/main/docs/manual/docs

# Copyright
copyright: Copyright &copy; 2001 - 2023 FAO-UN and others

extra_css:
  - assets/stylesheets/extra.css

# Configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/images/geonetwork-logo.svg
  favicon: assets/images/geonetwork-logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

# Page tree
nav:
  - 'GeoNetwork': index.md
  - 'Help':
    - help/index.md
    - 'Home page':
      - help/home/index.md
    - 'Search page':
      - help/search/index.md
    - 'Detail page':
      - help/record/index.md
    - 'Map page':
      - help/map/index.md
      - help/map/visualize/index.md

  - 'User Guide':
    - user-guide/index.md
    - user-guide/quick-start/index.md
    - user-guide/map/index.md
    - 'Describing Information':
      - user-guide/describing-information/index.md
      - user-guide/describing-information/creating-metadata.md
      - user-guide/describing-information/deleting-metadata.md
      - user-guide/describing-information/editing-metadata.md
      - user-guide/describing-information/importing-metadata.md
      - user-guide/describing-information/inspire-editing.md
      - user-guide/describing-information/managing-templates.md
      - user-guide/describing-information/multilingual-editing.md
    - 'Associating Resources':
      - user-guide/associating-resources/index.md
      - user-guide/associating-resources/cite.md
      - user-guide/associating-resources/doi.md
      - user-guide/associating-resources/linking-dataset-or-service.md
      - user-guide/associating-resources/linking-documents.md
      - user-guide/associating-resources/linking-feature-catalog.md
      - user-guide/associating-resources/linking-online-resources.md
      - user-guide/associating-resources/linking-others.md
      - user-guide/associating-resources/linking-parent.md
      - user-guide/associating-resources/linking-records.md
      - user-guide/associating-resources/linking-remote-records.md
      - user-guide/associating-resources/linking-source.md
      - user-guide/associating-resources/linking-thumbnail.md
      - user-guide/associating-resources/using-filestore.md
    - 'Tag information':
      - user-guide/tag-information/index.md
      - user-guide/tag-information/tagging-with-categories.md
      - user-guide/tag-information/tagging-with-keywords.md
    - 'Publishing':
      - user-guide/publishing/index.md
      - user-guide/publishing/managing-privileges.md
      - user-guide/publishing/restricting-information-to-metadata-sections.md
      - user-guide/publishing/transferring-privileges.md
    - 'Analyzing':
      - user-guide/analyzing/index.md
      - user-guide/analyzing/data.md
      - user-guide/analyzing/metadata.md
    - 'Workflow':
      - user-guide/workflow/index.md
      - user-guide/workflow/batchediting.md
      - user-guide/workflow/batchupdate-from-admin.md
      - user-guide/workflow/batchupdate-xsl.md
      - user-guide/workflow/batchupdate.md
      - user-guide/workflow/geopublication.md
      - user-guide/workflow/life-cycle.md
      - user-guide/workflow/suggestion.md
      - user-guide/workflow/validation.md
      - user-guide/workflow/versioning.md
    - 'Harvesting':
      - user-guide/harvesting/index.md
      - user-guide/harvesting/harvesting-csw.md
      - user-guide/harvesting/harvesting-filesystem.md
      - user-guide/harvesting/harvesting-geonetwork.md
      - user-guide/harvesting/harvesting-geoportal.md
      - user-guide/harvesting/harvesting-oaipmh.md
      - user-guide/harvesting/harvesting-ogcwxs.md
      - user-guide/harvesting/harvesting-sde.md
      - user-guide/harvesting/harvesting-simpleurl.md
      - user-guide/harvesting/harvesting-thredds.md
      - user-guide/harvesting/harvesting-webdav.md
      - user-guide/harvesting/harvesting-wfs-features.md
    - user-guide/export/index.md

  - 'Administration':
      - administrator-guide/index.md
      - 'Catalog':
        - administrator-guide/configuring-the-catalog/index.md
        - administrator-guide/configuring-the-catalog/system-configuration.md
        - administrator-guide/configuring-the-catalog/user-interface-configuration.md
        - administrator-guide/configuring-the-catalog/css-configuration.md
        - administrator-guide/configuring-the-catalog/csw-configuration.md
        - administrator-guide/configuring-the-catalog/portal-configuration.md
        - administrator-guide/configuring-the-catalog/inspire-configuration.md
        - administrator-guide/configuring-the-catalog/map-server-configuration.md
      - 'Users and Groups':
        - administrator-guide/managing-users-and-groups/index.md
        - administrator-guide/managing-users-and-groups/authentication-mode.md
        - administrator-guide/managing-users-and-groups/creating-group.md
        - administrator-guide/managing-users-and-groups/creating-user.md
        - administrator-guide/managing-users-and-groups/user-self-registration.md
      - 'Classification Systems':
        - administrator-guide/managing-classification-systems/index.md
        - administrator-guide/managing-classification-systems/managing-categories.md
        - administrator-guide/managing-classification-systems/managing-directories.md
        - administrator-guide/managing-classification-systems/managing-thesaurus.md
      - 'Metadata Standards':
        - administrator-guide/managing-metadata-standards/index.md
        - administrator-guide/managing-metadata-standards/configure-validation.md
        - administrator-guide/managing-metadata-standards/metadata-identifier.md
        - administrator-guide/managing-metadata-standards/standards.md

# Plugins - install using: pip3 install -r requirements.txt
plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
          site_name: 'GeoNetwork opensource (EN)'
        - locale: ru
          default: true
          name: Русский
          build: true
          site_name: 'GeoNetwork (RU)'
          site_description: Добро пожаловать на GeoNetwork. Данная документация разделена на отдельные гайды по различным темам.

          nav:
            - 'GeoNetwork': index.md

            - 'Помощь':
              - help/index.md
              - 'Главная страница':
                - help/home/index.md
              - 'Страница поиска':
                - help/search/index.md
              - 'Просмотр записи':
                - help/record/index.md
              - 'Страница карты':
                - help/map/index.md

            - 'Пользователям':
              - user-guide/index.md
              - user-guide/quick-start/index.md
              - user-guide/map/index.md
              - 'Описание информации':
                - user-guide/describing-information/index.md
                - user-guide/describing-information/managing-templates.md
                - user-guide/describing-information/creating-metadata.md
                - user-guide/describing-information/importing-metadata.md
                - user-guide/describing-information/editing-metadata.md
                - user-guide/describing-information/deleting-metadata.md
                - user-guide/describing-information/multilingual-editing.md
                - user-guide/describing-information/inspire-editing.md
              - 'Связывание со сторонними ресурсами':
                - user-guide/associating-resources/index.md
                - 'Связывание с документами':
                    - user-guide/associating-resources/linking-documents.md
                    - user-guide/associating-resources/using-filestore.md
                    - user-guide/associating-resources/linking-thumbnail.md
                    - user-guide/associating-resources/linking-online-resources.md
                - 'Связывание с другими записями':
                    - user-guide/associating-resources/linking-records.md
                    - user-guide/associating-resources/linking-parent.md
                    - user-guide/associating-resources/linking-source.md
                    - user-guide/associating-resources/linking-dataset-or-service.md
                    - user-guide/associating-resources/linking-feature-catalog.md
                    - user-guide/associating-resources/linking-others.md
                    - user-guide/associating-resources/linking-remote-records.md
                - user-guide/associating-resources/doi.md
                - user-guide/associating-resources/cite.md
              - 'Использование тегов':
                - user-guide/tag-information/index.md
                - user-guide/tag-information/tagging-with-categories.md
                - user-guide/tag-information/tagging-with-keywords.md
              - 'Публикация':
                - user-guide/publishing/index.md
                - user-guide/publishing/managing-privileges.md
                - user-guide/publishing/restricting-information-to-metadata-sections.md
                - user-guide/publishing/transferring-privileges.md
              - 'Анализ':
                - user-guide/analyzing/index.md
                - user-guide/analyzing/data.md
                - user-guide/analyzing/metadata.md
              - 'Рабочий процесс':
                - user-guide/workflow/index.md
                - 'Пакетное редактирование':
                  - user-guide/workflow/batchupdate.md
                  - user-guide/workflow/batchediting.md
                  - user-guide/workflow/batchupdate-from-admin.md
                  - user-guide/workflow/batchupdate-xsl.md
                - user-guide/workflow/geopublication.md
                - user-guide/workflow/life-cycle.md
                - user-guide/workflow/suggestion.md
                - user-guide/workflow/validation.md
                - user-guide/workflow/versioning.md
              - 'Сборщики данных':
                - user-guide/harvesting/index.md
                - user-guide/harvesting/harvesting-geonetwork.md
                - user-guide/harvesting/harvesting-csw.md
                - user-guide/harvesting/harvesting-ogcwxs.md
                - user-guide/harvesting/harvesting-filesystem.md
                - user-guide/harvesting/harvesting-geoportal.md
                - user-guide/harvesting/harvesting-oaipmh.md

                - user-guide/harvesting/harvesting-sde.md
                - user-guide/harvesting/harvesting-simpleurl.md
                - user-guide/harvesting/harvesting-thredds.md
                - user-guide/harvesting/harvesting-webdav.md
                - user-guide/harvesting/harvesting-wfs-features.md
              - user-guide/export/index.md

            - 'Администрирование':
              - administrator-guide/index.md
              - 'Каталог':
                - administrator-guide/configuring-the-catalog/index.md
                - administrator-guide/configuring-the-catalog/system-configuration.md
                - administrator-guide/configuring-the-catalog/user-interface-configuration.md
                - administrator-guide/configuring-the-catalog/css-configuration.md
                - administrator-guide/configuring-the-catalog/csw-configuration.md
                - administrator-guide/configuring-the-catalog/portal-configuration.md
                - administrator-guide/configuring-the-catalog/inspire-configuration.md
                - administrator-guide/configuring-the-catalog/map-server-configuration.md
              - 'Типы пользователей и Группы':
                - administrator-guide/managing-users-and-groups/index.md
                - administrator-guide/managing-users-and-groups/authentication-mode.md
                - administrator-guide/managing-users-and-groups/creating-group.md
                - administrator-guide/managing-users-and-groups/creating-user.md
                - administrator-guide/managing-users-and-groups/user-self-registration.md
              - 'Системы классификации метаданных':
                - administrator-guide/managing-classification-systems/index.md
                - administrator-guide/managing-classification-systems/managing-categories.md
                - administrator-guide/managing-classification-systems/managing-directories.md
                - administrator-guide/managing-classification-systems/managing-thesaurus.md
              - 'Стандарты метаданных':
                - administrator-guide/managing-metadata-standards/index.md
                - administrator-guide/managing-metadata-standards/configure-validation.md
                - administrator-guide/managing-metadata-standards/metadata-identifier.md
                - administrator-guide/managing-metadata-standards/standards.md

# Customizations
extra:
  version:
    provider: mike
    default: stable
  homepage: https://geonetwork-opensource.org/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geonetwork
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/_/geonetwork
    - icon: geonetwork/logo_bw
      link: https://geonetwork-opensource.org/
      name: GeoNetwork Website

# Extensions
# - These are carefully chosen to work with pandoc markdown support for whole document translation
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - md_in_html
